# .github/workflows/chromatic.yml

name: 'Chromatic'

# Event for the workflow
on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
        # Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Chromatic Project Token, go to the manage page of Chromatic to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
